# Generated by Django 2.2.6 on 2019-11-14 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Profile')),
                ('profile_pic', models.ImageField(upload_to='media/img/')),
                ('bio', models.CharField(max_length=500)),
            ],
            bases=('users.profile',),
        ),
    ]
