# Generated by Django 2.2.6 on 2020-03-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
