# Generated by Django 2.2.6 on 2019-11-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='zip',
            field=models.CharField(default='00000-0000', max_length=10),
        ),
    ]
