# Generated by Django 2.2.6 on 2019-11-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_location_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='zip',
            field=models.CharField(blank=True, default='60657', max_length=5, null=True),
        ),
    ]
