# Generated by Django 2.2.6 on 2019-12-02 18:31

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20191122_0322'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('events', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Location'),
        ),
    ]
