# Generated by Django 2.2.6 on 2019-12-04 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_all_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.PositiveIntegerField(choices=[(0, 'No Repeat'), (1, 'Days'), (2, 'Weeks'), (3, 'Months'), (4, 'Years')], default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='first_occurence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='frequency',
            field=models.PositiveIntegerField(default=1, verbose_name='Every number of...'),
        ),
    ]
