# Generated by Django 2.2.6 on 2019-12-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20191204_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='duration',
            new_name='units',
        ),
    ]
