# Generated by Django 2.2.6 on 2019-12-05 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20191204_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='first_occurence',
        ),
        migrations.RemoveField(
            model_name='event',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='event',
            name='units',
        ),
        migrations.CreateModel(
            name='RecurringEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.Event')),
                ('frequency', models.SmallIntegerField(default=1, verbose_name='Repeat every ___ <units>')),
                ('frequency_units', models.SmallIntegerField(choices=[(0, 'No Repeat'), (1, 'Days'), (2, 'Weeks'), (3, 'Months'), (4, 'Years')], default=0)),
                ('ends', models.SmallIntegerField(choices=[(0, 'after max. duration (5 years)'), (1, 'on ___'), (2, 'after ___ occurences')], default=0)),
                ('ends_on', models.DateField()),
                ('ends_after', models.PositiveIntegerField(verbose_name='Ends after ___ occurences')),
                ('first_occurence', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.RecurringEvent')),
            ],
            options={
                'abstract': False,
            },
            bases=('events.event',),
        ),
    ]
