# Generated by Django 2.2.6 on 2019-12-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20191205_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringevent',
            name='ends',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'after max. duration (5 years)'), (1, 'on ___'), (2, 'after ___ occurences')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recurringevent',
            name='ends_after',
            field=models.PositiveSmallIntegerField(verbose_name='Ends after ___ occurences'),
        ),
        migrations.AlterField(
            model_name='recurringevent',
            name='ends_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recurringevent',
            name='frequency',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Repeat every ___ <units>'),
        ),
        migrations.AlterField(
            model_name='recurringevent',
            name='frequency_units',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Days'), (1, 'Weeks'), (2, 'Months'), (3, 'Years')], default=0),
        ),
    ]
