# Generated by Django 2.2.6 on 2019-12-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20191205_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringevent',
            name='ends',
            field=models.PositiveSmallIntegerField(choices=[(0, 'after max. duration (5 years)'), (1, 'on ___'), (2, 'after ___ occurences')], default=0),
        ),
        migrations.AlterField(
            model_name='recurringevent',
            name='ends_after',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ends after ___ occurences'),
        ),
    ]
