# Generated by Django 2.2.6 on 2019-12-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20191205_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringevent',
            name='frequency_units',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Days'), (1, 'Weeks'), (2, 'Months'), (3, 'Years')], default=0, verbose_name='Repeat every <freq.> ___'),
        ),
    ]
