# Generated by Django 2.2.6 on 2019-12-06 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20191205_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringevent',
            name='ends',
        ),
        migrations.RemoveField(
            model_name='recurringevent',
            name='ends_after',
        ),
        migrations.RemoveField(
            model_name='recurringevent',
            name='ends_on',
        ),
        migrations.RemoveField(
            model_name='recurringevent',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='recurringevent',
            name='frequency_units',
        ),
    ]
