# Generated by Django 2.2.6 on 2020-01-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringevent',
            name='weekly',
            field=models.BooleanField(default=True),
        ),
    ]
