# Generated by Django 2.2.6 on 2020-01-15 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20200114_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringEventWeekday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RepeatInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('weekly', models.BooleanField(default=True)),
                ('frequency', models.PositiveSmallIntegerField(default=1)),
                ('frequency_units', models.PositiveSmallIntegerField(choices=[(0, 'No Repeat'), (1, 'Day(s)'), (2, 'Week(s)'), (3, 'Month(s)'), (4, 'Year(s)')], default=0)),
                ('ends', models.PositiveSmallIntegerField(choices=[(0, 'Ends after maximum duration (1 year)'), (1, 'Ends on date'), (2, 'Ends after number of occurences')], default=0)),
                ('ends_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('ends_after', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='recurringevent',
            name='info',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.RepeatInfo'),
        ),
        migrations.DeleteModel(
            name='RecurringEventInfo',
        ),
        migrations.AddField(
            model_name='recurringeventweekday',
            name='info',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.RepeatInfo'),
        ),
    ]
