# Generated by Django 2.2.6 on 2020-03-19 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20200313_1926'),
        ('events', '0025_auto_20200119_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.Album'),
        ),
    ]
