# Generated by Django 3.0.5 on 2020-05-12 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_location_no_kitchen'),
        ('images', '0008_auto_20200512_1857'),
        ('events', '0026_event_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Album'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.Location'),
        ),
    ]
