# Generated by Django 3.0.8 on 2020-10-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_auto_20200512_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='holiday',
            field=models.BooleanField(default=False),
        ),
    ]
