# Generated by Django 2.2.6 on 2020-01-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Nightlife'), (1, 'Restaurants'), (2, 'Arts & Entertainment'), (3, 'Health & Fitness'), (4, 'Sports'), (5, 'Non-profit')], default=0),
        ),
    ]
