# Generated by Django 3.0.5 on 2020-05-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='null', max_length=127),
            preserve_default=False,
        ),
    ]
