# Generated by Django 3.0.5 on 2020-05-12 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_auto_20200512_1857'),
        ('articles', '0006_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Album'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.AuthorImage'),
        ),
    ]
