# Generated by Django 3.0.5 on 2020-05-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20200514_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='facebook',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='instagram',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='twitter',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
