# Generated by Django 2.2.6 on 2020-01-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, null=True),
        ),
    ]
