# Generated by Django 2.2.6 on 2020-03-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_album_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='_image_hash',
            field=models.BinaryField(default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='_thumbnail_hash',
            field=models.BinaryField(default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(default=None, editable=False, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default=None, upload_to='img/%Y/%m/%d/'),
        ),
    ]
