# Generated by Django 3.0.5 on 2020-05-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20200313_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('_image_hash', models.BinaryField(default=None, max_length=16, null=True)),
                ('_thumbnail_hash', models.BinaryField(default=None, max_length=16, null=True)),
                ('prefix', models.CharField(blank=True, max_length=5, null=True)),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('suffix', models.CharField(blank=True, max_length=5, null=True)),
                ('bio', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='people/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(default=None, editable=False, null=True, upload_to='people/%Y/%m/%d/')),
            ],
            options={
                'verbose_name_plural': 'people',
            },
        ),
    ]
