# Generated by Django 3.0.5 on 2020-05-08 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('_image_hash', models.BinaryField(default=None, max_length=16, null=True)),
                ('_thumbnail_hash', models.BinaryField(default=None, max_length=16, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='people/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(default=None, editable=False, null=True, upload_to='people/%Y/%m/%d/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='person',
            name='_image_hash',
        ),
        migrations.RemoveField(
            model_name='person',
            name='_thumbnail_hash',
        ),
        migrations.RemoveField(
            model_name='person',
            name='image',
        ),
        migrations.RemoveField(
            model_name='person',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='person',
            name='profile_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.PersonImage'),
        ),
    ]
