# Generated by Django 3.0.5 on 2020-05-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_auto_20200512_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='homepage',
            field=models.BooleanField(default=False),
        ),
    ]
