# Generated by Django 3.0.5 on 2020-05-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_album_homepage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='homepage',
            new_name='feed',
        ),
        migrations.AddField(
            model_name='album',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Nightlife'), (1, 'Restaurants'), (3, 'Arts & Entertainment'), (4, 'Health & Fitness'), (5, 'Sports'), (6, 'Non-profit'), (7, 'Editorials & Opinions')], default=0),
        ),
    ]
