# Generated by Django 3.0.7 on 2020-06-09 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_auto_20200520_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('_image_hash', models.BinaryField(default=None, max_length=16, null=True)),
                ('_thumbnail_hash', models.BinaryField(default=None, max_length=16, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='contacts/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(default=None, editable=False, null=True, upload_to='contacts/%Y/%m/%d/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=70)),
                ('prefix', models.CharField(blank=True, max_length=5, null=True)),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('suffix', models.CharField(blank=True, max_length=5, null=True)),
                ('bio', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('facebook', models.CharField(blank=True, max_length=70, null=True)),
                ('twitter', models.CharField(blank=True, max_length=70, null=True)),
                ('instagram', models.CharField(blank=True, max_length=70, null=True)),
                ('title', models.CharField(max_length=70)),
                ('profile_image', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.ContactImage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
