# Generated by Django 2.2.6 on 2020-03-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('prefix', models.CharField(blank=True, max_length=5, null=True)),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('suffix', models.CharField(blank=True, max_length=5, null=True)),
                ('image', models.ImageField(default=None, upload_to='people/')),
                ('_image_hash', models.BinaryField(blank=True, default=None, max_length=16, null=True)),
                ('bio', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'people',
            },
        ),
    ]
