# Generated by Django 2.2.6 on 2020-03-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200311_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='_image_hash',
            field=models.BinaryField(default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='_thumbnail_hash',
            field=models.BinaryField(default=None, max_length=16, null=True),
        ),
    ]
