# Generated by Django 3.0.5 on 2020-04-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200313_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
