# Generated by Django 3.0.5 on 2020-05-07 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_person_website'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
