# Generated by Django 2.2.6 on 2019-12-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100, null=True),
        ),
    ]
