# Generated by Django 2.2.6 on 2019-12-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20191226_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, max_length=100, null=True),
        ),
    ]
