# Generated by Django 2.2.6 on 2020-02-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_neighborhood_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='override_slug',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
