# Generated by Django 3.0.3 on 2020-02-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_location_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Nightlife'), (1, 'Restaurants'), (2, 'Bar & Restaurant'), (3, 'Arts & Entertainment'), (4, 'Health & Fitness'), (5, 'Sports'), (6, 'Non-profit')]),
        ),
    ]
