# Generated by Django 2.2.6 on 2020-02-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_auto_20200226_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Nightlife'), (1, 'Restaurants'), (2, 'Nightlife & Restaurants'), (3, 'Arts & Entertainment'), (4, 'Health & Fitness'), (5, 'Sports'), (6, 'Non-profit')]),
        ),
    ]
